### ISSUE TITLE
oauth2client no longer uses SignedJwtAssertionCredentials

### ISSUE THREAD

**Issue by SanFranciscoSunrise** [googleplus/gplus-domains-quickstart-python#3]
domain_delegation.py as part of the gplus-domains-quickstart-python program and got an error message:
upon running #>python domain_delegation.py

"ImportError: cannot import name SignedJwtAssertionCredentials"

Upon a little investigation I found this:

https://github.com/google/oauth2client/issues/401

Unfortunately I do not have the time to fork and edit the code into a working status right now as this is just a hobby for me.  I'm guessing that as part of the overall Google+ documentation this will need to be fixed regardless.  Please look into the fix and let me know when an updated version of the code is complete and ready to run.

**Comment by vicfryzel** [comment]
@samtstern can you forward appropriately?

**Comment by samtstern** [comment]
@vicfryzel merged a PR that should fix this.
